### PR TITLE
Update pollard_rho_algorithm.py

### PR DESCRIPTION
**Pull request by YuvarajCB**

### CODE REVIEW

**Comment by chinmaydd** [comment]
@YuvarajCB Please update the PR for merging ASAP.

**Comment by chinmaydd** [comment]
Looks fine, but there is work to be done for integrating it with the main tool.

**Comment by chinmaydd** [comment]
@YuvarajCB Check the other PR raised by @PrabhanjanPM. Please modify the daedalus.py file accordingly and raise an updated PR. Please do so by 5 today.

**Comment by YuvarajCB** [comment]
I checked locally on system and imported also. It is working fine. Sorry
for delay

**Comment by chinmaydd** [comment]
@YuvarajCB Cool :+1:

**Pull request merged**
